# Base profiel (generiek, voor alle klanten)
layout:
  title_block: "rechtsonder"

labels:
  material: ["Materiaal","Material","Material grade","Grade","Quality","Qualiteit","Mat."]
  finish: ["Finish","Afwerking","Surface treatment","Surface finish","Post-treatment","Coating"]
  weld_finish: ["Weld finish","Lasafwerking","Surface grind after welding","flush ground","dressed","smoothed","machined"]
  welding_designation: ["Weld","Welding","Las","Welding designation","EN ISO 2553","DIN EN ISO 2553"]
  tolerances: ["Toleranties","Tolerance","Tolerances","General tolerance","Afwijking","tol.","±"]
  notes: ["Notes","Remarks","Opmerkingen"]

whitelists:
  material_grade:
    - "St.37"   # klassiek staal
    - "S235"    # S-series
    - "S275"
    - "S355"
    - "S460"
    - "1.0038"  # EN nummers
    - "1.0570"
    - "304"     # RVS/AISI
    - "316"
    - "316L"
    - "1.4301"
    - "1.4404"
    - "AlMg3"   # Aluminium
    - "EN AW-5754"
    - "EN AW-6082"
    - "DX51D"   # Overig
    - "Q235"
    - "Q345"
  post_treatment:
    - "Bead blasted"
    - "Electro galvanized"
    - "Hot-dip galvanized"
    - "Zinc plated"
    - "Powder coated"
    - "Powder coating"
    - "Anodized"
    - "Painted"
  weld_finish:
    - "Surface grind after welding"
    - "flush ground"
    - "dressed"
    - "smoothed"
    - "machined"

blacklist:
  not_material: ["A0","A1","A2","A3","A4","A5","Sheet size","Scale","Bladnr","Rev","Revision"]

notes_cues: ["Notes","Remarks","Opmerkingen"]
